### ISSUE TITLE
[회원가입 페이지 구현] 프로필 아이콘 리사이징

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv-main#39]
> https://github.com/GiveUsMoney/FanFixiv/issues/48 참고

**Task 설명**
현재 회원가입 프로필 이미지의 경우 업로드한 크기 그대로 S3에 저장됩니다. 하지만 실제 사이즈 그대로 S3에 업로드 하는 것은 비효율적이며 비용적으로도 문제가 있기에 회원가입 이후 프로필 이미지는 40x40사이즈로 리사이징을 진행후 저장합니다.

추가) AWS lambda를 이용하여 해당 기능을 구현합니다.

**TODO**

- [ ] ~~S3 임시 디렉토리에서 프로필 아이콘 가져오기~~
- [ ] ~~프로필 아이콘 리사이징~~
- [ ] ~~프로필 아이콘 S3에 다시 저장~~
- [x] AWS lambda로 `/profile` 경로에 있는 이미지 리사이징

**레퍼런스**
- https://kosaf04pyh.tistory.com/334

**추가적인 설명**
AWS lambda를 이용해 해당 issue를 해결할수 있습니다. 이에 대해서는 깊은 논의가 필요합니다.

**Comment by Roharui** [comment]
해당 issue는 PR이 따로 존재하지 않기에 바로 close 하도록 하겠습니다.
