### ISSUE TITLE
[검색 기능] 엑스트라 태그(검색용 태그) 대응

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv-main#49]
> https://github.com/GiveUsMoney/FanFixiv/issues/60 참고

**Task 설명**
엑스트라 태그에 대한 검색 로직을 구현합니다.

**TODO**

- [x] 인기 태그 구현
- [x] 좋아요 태그 구현
- [ ] ~~선호 태그 구현~~ (프로필 기능이 완료되고 구현합니다.)

**레퍼런스**
- https://typeorm.io/

**추가적인 설명**
상황에 따라 DB의 구조를 변경할수도 있으니 구조가 변경되면 바로바로 [ERD](https://www.erdcloud.com/)에 반영하도록 합시다.
