### ISSUE TITLE
[컨텐츠 카드] 상세 보기 API 구현

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv-main#55]
> https://github.com/GiveUsMoney/FanFixiv/issues/54 참고

**Task 설명**
컨텐츠 카드에 있는 더보기 아이콘을 누를 경우 해당하는 컨텐츠의 상세 정보를 표시하는 기능이 존재. 그 기능의 API를 구현함.

**TODO**

- [x] 컨텐츠 카드 조회 기능
    - [x] 모든 태그 표시
    - [x] 등록일 표시
    - [x] 원작 출처 표시
    - [x] 번역가 출처 표시

**레퍼런스**
- https://typeorm.io/

**추가적인 설명**
DB 수정이 이루어 지는 기능이므로 ERD를 수정하도록 합시다.
